--
--Delete FROM roles where name = 'ROLE_USER';
--Delete FROM roles where name = 'ROLE_ADMIN';
--
--INSERT INTO roles(name) VALUES('ROLE_USER');
--INSERT INTO roles(name) VALUES('ROLE_ADMIN');
--
--
--
